[package]
name = "kompass"
version = "0.4.0"
edition = "2024"
rust-version = "1.95"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
ignore = "0.4"
proc-macro2 = { version = "1.0", features = ["span-locations"] }
ruff_python_ast = "=0.0.10"
ruff_python_parser = "=0.0.10"
ruff_source_file = "=0.0.10"
ruff_text_size = "=0.0.10"
quote = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
syn = { version = "2.0", features = ["full", "visit"] }
